'use strict';

const models = require('../models');

module.exports = {
  up: (queryInterface, Sequelize) => {
    return models.User.bulkCreate([{
      title: 'Mme',
      lastName: 'Jolivet',
      firstName: 'Karine',
      address: '11 rue de Poissy 75011 Paris',
      phone: '0666666666',
      dateOfBirth: null,
      receiverBond: null,
      email: 'karine.jolivet@gmail.com',
      password: 'karine',
      preferenceOfContact: 'EMAIL',
      numberOfSubscriptions: 1,
      selectedReceiverId: 2,
      subscriber: true,
      isAdmin: true,
      status: true,
      avatar: null,
      createdAt: '2019-01-14T10:24:29.956Z',
      updatedAt: '2019-01-14T10:24:29.956Z',
    },
    {
      title: 'M.',
      lastName: 'Jolivet',
      firstName: 'Maurice',
      address: '12 rue de Poissy 75011 Paris',
      phone: '0666666666',
      dateOfBirth: '01/01/1935',
      receiverBond: 'père',
      email: null,
      password: null,
      numberOfSubscriptions: 0,
      selectedReceiverId: -1,
      subscriber: false,
      isAdmin: false,
      status: true,
      avatar: '../../assets/avatar_old_man.png',
      createdAt: '2019-01-14T10:24:29.956Z',
      updatedAt: '2019-01-14T10:24:29.956Z',
    },
    {
      title: 'Mme',
      lastName: 'Jolivet',
      firstName: 'Mauricette',
      address: '12 rue de Poissy 75011 Paris',
      phone: '0666666666',
      dateOfBirth: '02/02/1940',
      receiverBond: 'mère',
      email: null,
      password: null,
      numberOfSubscriptions: 0,
      selectedReceiverId: -1,
      subscriber: false,
      isAdmin: false,
      status: true,
      avatar: '../../assets/avatar_old_woman.png',
      createdAt: '2019-01-14T10:24:29.956Z',
      updatedAt: '2019-01-14T10:24:29.956Z',
    },
    {
      title: 'M.',
      lastName: 'Doe',
      firstName: 'John',
      address: '13 rue de Poissy 75011 Paris',
      phone: '0666666666',
      dateOfBirth: '03/03/1937',
      receiverBond: 'oncle',
      email: null,
      password: null,
      numberOfSubscriptions: 0,
      selectedReceiverId: -1,
      subscriber: false,
      isAdmin: false,
      status: true,
      avatar: '../../assets/avatar_old_man.png',
      createdAt: '2019-01-14T10:24:29.956Z',
      updatedAt: '2019-01-14T10:24:29.956Z',
    }], {});
  },
  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Users', null, {});
  },
};
